###
# @name hello
# @no-log
GET {{host}}/say

###
# @name 添加用户
# @no-log
GET {{host}}/user/add-user

###
# @name 删除用户
# @no-log
DELETE {{host}}/user/del-user

###
# @no-log
# @name 添加用户2
POST localhost:64775/user/add2

###
# @no-log
# @name  获取查询参数
GET {{host}}:52875/user/inner-user/params?name=zhangsan&age=10

###
# @no-log
# @name  获取form数据参数
PUT 127.0.0.1:9000/user/inner-user/params
Content-Type: application/x-www-form-urlencoded

username = zhangsan1111 &
password = 123456111aa

###
# @no-log≠≠≠
# @name  获取form数据参数
PUT {{host}}/user/inner-user/params
Content-Type: application/json

{
  "name": "王老五",
  "password": "zhangxueyou"
}

###
# @no-log≠≠≠
# @name  测试相应
PUT {{host}}/user/inner-user/response
Content-Type: application/json

{
  "name": "王老五",
  "password": "zhangxueyou"
}
