###
# @name hello
# @no-log
GET {{host}}/say

###
# @name 添加用户
# @no-log
GET {{host}}/user/add-user

###
# @name 删除用户
# @no-log
DELETE {{host}}/user/del-user

###
# @no-log
# @name 添加用户2
POST {{host}}/user/add2